### ISSUE TITLE
Read address and port of discovered services

### ISSUE THREAD

**Issue by saket** [devgianlu/zeroconf-java#16]
When `zeroconf` announces itself, it includes details about its address and its port. Is this something that `zeroconf` can read about other devices when discovering them? 

```
Announced Service{alias='alias', service='http', port=8080, text={}, addresses=[/192.168.xx.xx], domain='.local', protocol='tcp', host='host'}.
```

I'm currently broadcasting this information by using `Service#setText` and reading it back using `DiscoveredService#getRelatedRecords()`. Is there a better way of doing this?

**Comment by devgianlu** [comment]
That's the only way right now. Do you have a better API idea in mind? I made this one up very quickly.

**Comment by saket** [comment]
What do you think of making properties of `DiscoveredService`? 

```kotlin
discoveredService.addresses
discoveredService.port
```

**Comment by devgianlu** [comment]
I have pushed some code, does that fit your needs?

**Comment by saket** [comment]
This looks great! Thank you for maintaining this library btw. It is so much simpler to use over everything else.
