### ISSUE TITLE
ConcurrentModificationException when reading discovered services

### ISSUE THREAD

**Issue by saket** [devgianlu/zeroconf-java#17]
Hey @devgianlu, I am frequently running into `ConcurrentModificationException` when using `DiscoveredServices#getServices()`. From what I understand, this is happening because `Collections.unmodifiableCollection()` holds a reference to the original list, not protecting it from reads from another thread. Thoughts on returning a **new** list instead?

**Comment by saket** [comment]
Thanks for fixing this. Is this available on `1.3.3-SNAPSHOT`?

**Comment by devgianlu** [comment]
Yup: https://oss.sonatype.org/content/repositories/snapshots/xyz/gianlu/zeroconf/zeroconf/1.3.3-SNAPSHOT/

**Comment by saket** [comment]
Wanna make the same fix for this usage? https://github.com/devgianlu/zeroconf-java/blob/d6cad78439333c7a97b7a15c2e4d298daf2db423/src/main/java/xyz/gianlu/zeroconf/Zeroconf.java#L578

**Comment by devgianlu** [comment]
Done!
