### ISSUE TITLE
Devices that have already announced themselves before scanning aren't discovered

### ISSUE THREAD

**Issue by saket** [devgianlu/zeroconf-java#18]
Hey @devgianlu, I have just started testing my app on multiple devices and I noticed that `zeroconf` doesn't seem to pick nearby devices that had announced themselves I started scanning for them. 

```
1. Device A announces itself.
2. Device B starts scanning for nearby devices. It doesn't discover A yet.
4. Device A announces itself again (I'm recreating Zeroconf's instance).
5. Device B picks up A.
```

Is this an expected behavior? I can think of repeatedly sending announcements but that doesn't like a great idea, especially considering each announcement takes ~2s to go out.

**Comment by devgianlu** [comment]
> A Multicast DNS responder MUST NOT send announcements in the absence
   of information that its network connectivity may have changed in some
   relevant way.  In particular, a Multicast DNS responder MUST NOT send
   regular periodic announcements as a matter of course.

From: https://datatracker.ietf.org/doc/html/rfc6762#section-8.3

Device B should be able to discover device A by sending a query to which device B should respond. Device A will send queries as described in https://datatracker.ietf.org/doc/html/rfc6762#section-5.2. There might be bugs in some places.

**Comment by saket** [comment]
Got it. After spending some time on this, I think the problem is something else: zeroconf's announcement isn't getting broadcasted to other devices when it is run on my Android phone. Where should I look if I wanna investigate this? It works great when run as a desktop app.

I can confirm that I'm able to discover my phone correctly when I use [Android's APIs](https://developer.android.com/training/connect-devices-wirelessly/nsd). I _can_ use it, but I am trying really hard to use a single piece of code that works on all JVM platforms.

**Comment by devgianlu** [comment]
It looks like Android is not able to resolve the `.local` suffix, but I am not entirely sure this is your issue. You could try capturing the network with wireshark too see if packets are going to `224.0.0.251`.
