### ISSUE TITLE
Announcements not sticky

### ISSUE THREAD

**Issue by Erhannis** [devgianlu/zeroconf-java#5]
I'm not _sure_ what the expected behavior is (nor terminology), but it seems like, having announced a service, any new listeners should become aware of the service in short order, until the service is canceled.  I think it used to work, while I was using JmDNS for announcing services.  (But then it failed to announce properly on one of my computers, binding instead to 127.0.1.1, so I switched to zeroconf-java, which DOES work on all my computers so far.)  Consider the program I'm writing: https://github.com/Erhannis/LanCopy .  If I start two instances of it, ~30 seconds apart, the first sees the other come online, but the second doesn't see the first, even after several minutes of waiting.  Is there a parameter I need to set?  Something else?

**Comment by devgianlu** [comment]
How are you looking for the other service?

**Comment by Erhannis** [comment]
Update: the problem does not occur consistently.

To answer your question, I do the following:

```java
    Zeroconf zeroconf0 = null;
    Service zcService0 = null;
    try {
      zeroconf0 = new Zeroconf();
      zeroconf0.addAllNetworkInterfaces()
               .setUseIpv4(true)
               .setUseIpv6(false);

      zcService0 = new Service(ID, "lancopy", PORT);
      zeroconf0.announce(zcService0);
    } catch (IOException ex) {
      Logger.getLogger(JmDNSProcess.class.getName()).log(Level.SEVERE, null, ex);
    }
    this.zeroconf = zeroconf0;
    this.zcService = zcService0;

    JmDNS jmdns0 = null;
    try {
      // Create a JmDNS instance
      jmdns0 = JmDNS.create(InetAddress.getLocalHost());

      jmdns0.addServiceListener("_lancopy._tcp.local.", new LCListener(dataOwner, ID, wsClient));
    } catch (IOException e) {
      System.out.println(e.getMessage());
    }
    this.jmdns = jmdns0;
```

Note that the first block is zeroconf-java, announcing a service, and the second block is JmDNS, looking for all such services.  (This would be run on multiple computers, and each program filters out its own id.  `ID` looks like `LanCopy-615ae3-525f5f...` etc.)

**Comment by Erhannis** [comment]
To clarify my note that the problem does not occur consistently, I was testing just now and noticed that, in fact, the second instance to run DID immediately display the first instance.  I've restarted both, and they're registering each other just fine.  Any idea why they weren't?

**Comment by devgianlu** [comment]
Honestly I am completely lost when talking about mDNS not working. I refactored some code I found around into this one because I had the same problem of dispatching not working reliably and this seemed to do the job.

What I figured out was that if it appeared on `dns-sd` then it was going to work everywhere at some point.

**Comment by devgianlu** [comment]
@Erhannis Did you figure this out eventually?
