### ISSUE TITLE
Race condition

### ISSUE THREAD

**Issue by Erhannis** [devgianlu/zeroconf-java#7]
Something weird - so my program https://github.com/Erhannis/LanCopy so far works fairly reliably on Windows and Linux, but for some reason on Mac I'm getting what I think is some kind of race condition / deadlock.  Consider the following screenshots, and notice the monitors listed on the left:

<img width="1440" alt="Screen Shot 2021-03-31 at 6 35 06 PM" src="https://user-images.githubusercontent.com/3024589/113222433-080edf80-9255-11eb-9816-e2e2991bbb14.png">
<img width="1440" alt="Screen Shot 2021-03-31 at 6 36 19 PM" src="https://user-images.githubusercontent.com/3024589/113222437-0b09d000-9255-11eb-8909-dda4a9939e0b.png">

`addAllNetworkInterfaces` is (ultimately) trying to synchronize on `publicKeys`, but apparently the `Zeroconf$ListenerThread` already has a lock on it, and (for some reason) won't let go.  I've let it run for at least a minute or two, and it hasn't resolved.  However, if I put a breakpoint on Zeroconf:645 (other locations may work), and wait a few seconds, the rest of the threads appear to do their thing and the app starts up, and then I can remove the breakpoint and continue, and the program seems to work as it should.

I don't know what exactly is causing this.  It acts like a deadlock, but the locks don't look like a deadlock - just, for some reason the `kevent0` call never returns.  How it gets triggered on this computer but not the others - maybe some kind of permissions check takes longer on this Mac (I don't have admin), or...something?  Dunno.  So, I'm not sure what the best fix is.  But, it MIGHT make the problem go away if you added a timeout to Zeroconf.java:646 `selector.select();`, and wrapped it in a loop.  However, I'm not sure what check you'd need to make - not sure if a timeout throws an exception, or just makes e.g. `.selectedKeys()` turn up empty.

**Comment by devgianlu** [comment]
I believe  [this](https://stackoverflow.com/questions/1057224/java-thread-blocks-while-registering-channel-with-selector-while-select-is-cal/2179612#2179612) is what's happening. Either I synchronize manually with an external lock or build a queue of operations. I think the first one is easier.

**Comment by Erhannis** [comment]
Ah, that looks right.  Lemme know when that's done - thanks!

**Comment by devgianlu** [comment]
I pushed a fix as described in the StackOverflow question, let me know if it works for you.

**Comment by Erhannis** [comment]
I think just adding a `wakeup` call there still leaves a race condition.  (It probably improves things, at least - but still could deadlock once in a while.)  I'm reading up on the issue (it's a pretty obnoxious problem); if I come up with a better fix I'll make a pull request.
